#mk main environment Debug Config

ServerName localhost
Listen 8080
PidFile tmp/httpd.pid

IncludeOptional /media/araki-mk/DATA/VSP/Projects/httpdlib_load/*.load
IncludeOptional /media/araki-mk/DATA/VSP/Projects/httpdlib_load/*.conf

LogLevel info
ErrorLog ./log/wp_error.log
LogFormat "%h %l %u %t \"%r\" %>s %b" common

DocumentRoot /media/araki-mk/DATA/VSP/Projects/webMusic

AddType application/x-httpd-php .php
DirectoryIndex index.html index.php